import re
from typing import Optional
import asyncio
from app.rag.vectorstore import vectorstore

from langchain_core.documents import Document

"""  
    The default retrieval pass usually returns documents of type semantic_query which is a simulated user query. These documents are LLM generated synthetic queries created for each movie in order to simulate the kinds of questions or descriptions a user might write. This improves semantic matching, because a user query can match a generated query even when the original plot uses different wording.

    However, when the top-k value is relatively small, for example k=20, the default retrieval often returns mostly synthetic query documents and may not retrieve enough real plot or summary context. For that reason, the system performs a second retrieval pass that specifically filters for documents where doc_type = "summary". These summary documents contain condensed plot information and provide more direct context about the actual movie. 

    Retrieved summaries docs aren't always the summaries of retrieved generated queries but the most cosine similar with user's query.  
    This means that the same movie can be retrieved through both a synthetic query and its plot summary. When that happens, it is a stronger signal that the movie is relevant. The synthetic query matches the user's intent, while the summary provides real story context to support the recommendation.

    Total retrieved docs are 20. 15 documents without extra filter(usuallly generated queries) and 5 documents with filter doc_type = summary context. 
    
    After retrieval, another LLM receives all retrieved results, including synthetic queries and summaries, and judges which movies best match the user's request. The final recommendation is therefore not based only on vector similarity, but also on an LLM reasoning step that compares the retrieved evidence and decides which movies should be recommended.

    Search movies in Chroma with two retrieval passes with extra filter run concurrently with asyncio.gather:

    Retrieval passes:

    1. Retrieve 15 documents without doc_type filter.
       In practice these are usually semantic/synthetic simulated query docs.
       
    2. Retrieve 5 documents with filter doc_type="summary" which is the summary of movie plot.

    Normal metadata filters such as genres, excluded_genres, director, and year
    are still applied to both retrieval passes if user explicit requests.    

    (At this time i dont use doc_type filter for retrieve generated queries because usually are much retrieved first, i dont have yet chunks but i could split plots into paragraphs which is too long descriptions (chunk-paragraph might be over than 2000 charachters and in future i could generate more simulated quries for each chunk-paragraph ant to increase a litle bit the temperature 0.2-0.3 with carefully prompting to recognize vibes,mood,emotion not just direct plot description, and also make evidence-reasoning by real plot paragraph and additionaly generate tags or score response. Then it might need more complex filter cases or rerank) as example structured output:
{
    "synthetic_query":
        "What movie has a rebel betray his crew because he wants to return to a comfortable fake reality?",
    "evidence":
        "Cypher betrays Morpheus to Smith in exchange for a comfortable life back in the Matrix.",
    "focus": ["betrayal", "conflict", "psychological temptation"]
},
{
    "synthetic_query": "What sci-fi movie is about humans trapped in a simulated world while machines harvest their bodies for energy?",
    "evidence": "The Matrix is a simulation where harvested humans are trapped and pacified while machines use their bioelectric power.",
    "focus": ["machine control", "dystopia", "simulation","worldbuilding"]
}

    Above examples: synthetic_query is simulated query generated by llm for a chunk-paragraph, evidence is the context of each concrete chunk-paragpraph or summary, and focus are tags recognizing by llm.
    user can asks about psychological temptation, machine control...

    The plots that i managed to find, were too long for my project idea and consists of some long paragraphs and one paragraph migth have over than 2000 charachters. Unhappily these contents focus mainly in plot description and less in atmosphere, mood,vibes, emotionals such as small descriptions in movie websites could be embedded in one vector, which challenging the implementation of my idea (for making only 1 vector for each plot and one synthetic query about this and retrieve atmosphere, or emotionals as usually provided in such small descriptions) .
"""

DEFAULT_TOP_K = 15
SUMMARY_K = 5

def normalize_key(value: str) -> str:
    """
    Normalize a free-text value so it can be safely used as part of a Chroma
    metadata key.

    Example:
    "Sci-Fi" -> "sci_fi"

    This is used mainly for genre flags such as:
    genre_sci_fi = True
    """
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_")


def build_chroma_filter(
    genres: list[str] | None = None,
    excluded_genres: list[str] | None = None,
    director: Optional[str] = None,
    year: Optional[int] = None,
) -> dict | None:
    """
    Build the base Chroma metadata filter from the user's explicit filters.

    Supported filters:
    - included genres: require genre_name == True
    - excluded genres: require genre_name != True
    - director: exact director match
    - year: exact year match

    Examples:
    - A dark sci fi movie where the hero discovers a simulated reality
    - Ταινίες που δεν ειναι scient fiction και προκαλούν anxiety και tension συνεχώς 

    Returns:
    - None, if no filters were provided
    - a single condition dict if there is only one condition
    - {"$and": [...]} if multiple conditions must all be true
    """

    conditions = []

    for genre in genres or []:
        conditions.append({f"genre_{normalize_key(genre)}": True})

    for genre in excluded_genres or []:
        conditions.append({f"genre_{normalize_key(genre)}": {"$ne": True}})

    if director:
        conditions.append({"director": director})

    if year:
        conditions.append({"year": year})

    if not conditions:
        return None

    if len(conditions) == 1:
        return conditions[0]

    return {"$and": conditions}


def combine_chroma_filters(*filters: dict | None) -> dict | None:
    """
    Combine multiple Chroma filters into one valid Chroma filter.

    This is useful when we already have a base filter from user constraints
    (genres, director, year) and we also want to add an extra internal filter,
    for example:
    {"doc_type": "summary"}

    If a filter is already an {"$and": [...]} filter, its inner conditions are
    flattened so we do not create unnecessary nested $and blocks.

    Returns:
    - None if all filters are empty
    - the single filter if only one exists
    - {"$and": [...]} if multiple filters must be combined
    """
    conditions = []

    for filter_item in filters:
        if not filter_item:
            continue

        if (
            isinstance(filter_item, dict)
            and set(filter_item.keys()) == {"$and"}
            and isinstance(filter_item["$and"], list)
        ):
            conditions.extend(filter_item["$and"])
        else:
            conditions.append(filter_item)

    if not conditions:
        return None

    if len(conditions) == 1:
        return conditions[0]

    return {"$and": conditions}


async def retrieve_docs(
    semantic_query: str,
    genres: list[str] | None = None,
    excluded_genres: list[str] | None = None,
    director: Optional[str] = None,
    year: Optional[int] = None,
    k: int = DEFAULT_TOP_K,
    extra_filter: dict | None = None,
) -> list[Document]:
    """
    Run one semantic retrieval pass against the Chroma vectorstore.

    This function:
    - Builds the base metadata filter from user filters.
    - Combines it with an optional extra filter.
    - Creates a Chroma retriever with the final k and filter.
    - Executes the async retrieval using retriever.ainvoke(...).

    The returned values are raw LangChain Document objects, not final movie dicts.
    Conversion to API dicts is done separately in docs_to_movie_results.
    """

    base_filter = build_chroma_filter(
        genres=genres or [],
        excluded_genres=excluded_genres or [],
        director=director,
        year=year,
    )

    final_filter = combine_chroma_filters(base_filter, extra_filter)

    search_kwargs = {"k": k}

    if final_filter:
        search_kwargs["filter"] = final_filter

    retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs=search_kwargs,
    )

    return await retriever.ainvoke(semantic_query)


def docs_to_movie_results(
    docs: list[Document],
    retrieval_source: str,
) -> list[dict]:
    """
    Convert raw LangChain Document results from Chroma into plain dictionaries
    used by the rest of the RAG graph.

    Each result keeps:
    - movie metadata such as movie_id, title, genres, year, director
    - doc_type, so we know whether the retrieved item is summary, full plot,
    semantic query, etc.
    - retrieval_source, so we know which retrieval pass returned it
    - page_content/plot, which contains the retrieved text itself

    The plot field is kept for compatibility with the rest of the existing code,
    even though the content may be a summary or semantic query depending on doc_type.
    """    
    results = []

    for doc in docs:
        doc_type = doc.metadata.get("doc_type", "")

        results.append(
            {
                "movie_id": doc.metadata.get("movie_id"),
                "title": doc.metadata.get("title"),
                "genres": doc.metadata.get("genres"),
                "year": doc.metadata.get("year"),
                "director": doc.metadata.get("director"),
                "doc_type": doc_type,
                "retrieval_source": retrieval_source,
                "page_content": doc.page_content,
                "plot": doc.page_content,
            }
        )

    return results

async def search_movies(
    semantic_query: str,
    genres: list[str] | None = None,
    excluded_genres: list[str] | None = None,
    director: Optional[str] = None,
    year: Optional[int] = None,
    default_k: int = 15,
    summary_k: int = 5,
) -> list[dict]:
    """
    Search movies in Chroma with two retrieval passes with extra filter run concurrently with asyncio.gather:   
   
    1. Retrieve 15 documents without doc_type filter.
       In practice these are usually the simulated semantic/synthetic query docs.

    2. Retrieve 5 documents with doc_type="summary" which is the summary of movie plot.

    Normal metadata filters such as genres, excluded_genres, director, and year
    are still applied to both retrieval passes.
    """

    # default retrieve task usually retrieve only semantic queries which were generated by llm 
    primary_task = retrieve_docs(
        semantic_query=semantic_query,
        genres=genres,
        excluded_genres=excluded_genres,
        director=director,
        year=year,
        k=default_k,
        extra_filter=None,
    )



    # this task retrieve only filtered summaries of movie plots using cosine similariity with user'squery. 
    summary_task = retrieve_docs(
        semantic_query=semantic_query,
        genres=genres,
        excluded_genres=excluded_genres,
        director=director,
        year=year,
        k=summary_k,
        extra_filter={"doc_type": "summary"},
    )

    primary_docs, summary_docs = await asyncio.gather(
        primary_task,
        summary_task,
    )

    return (
        docs_to_movie_results(primary_docs, retrieval_source="semantic documents")
        + docs_to_movie_results(summary_docs, retrieval_source="semantic summaries")
    )

